services:
  api:
    container_name: fastapi
    build:
      context: .
      dockerfile: ./docker/dev.dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./api:/app
    env_file:
      - ./.env
    environment:
      - SUPABASE_URL=${SUPABASE_URL?Create and fill .env file}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY?Create and fill .env file}
