services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    env_file:
      - ./.env.dev
    environment:
      - SUPABASE_URL=${SUPABASE_URL?Create and fill .env file}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY?Create and fill .env file}
    command: uvicorn main:app --host 0.0.0.0 --port 9000 --reload
